---
cifmw_baremetal_hosts:
  compute-0:
    password: calvin
    username: root
    connection: "ipmi://rhos-nfv-12-drac.mgmt.lab.eng.rdu2.redhat.com"
    boot_mode: UEFI
    nics:
      - mac: "2C:EA:7F:F7:36:AB"
        network: provision
