apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-sriov
spec:
  services:
    - bootstrap
    - download-cache
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - run-os
      # - reboot-os
    - install-certs
    - ovn
    - neutron-sriov
    - libvirt
    - nova-custom-sriov
  baremetalSetTemplate:
    osImage: edpm-hardened-uefi.qcow2
    osContainerImageUrl: registry.access.redhat.com/rhosp-dev-preview/edpm-hardened-uefi-rhel9:18.0.0-9
    bmhLabelSelector:
      app: sriov
    ctlplaneInterface: eno2
    cloudUserName: cloud-admin
    provisioningInterface: enp1s0
    passwordSecret:
      name: baremetalset-password-secret
      namespace: openstack
  nodes:
    edpm-compute-1:
      hostName: edpm-compute-1
  networkAttachments:
    - ctlplane
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    networks:
      - name: ctlplane
        subnetName: subnet1
        defaultRoute: true
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
    managementNetwork: ctlplane
    ansible:
      ansibleVars:
         edpm_bootstrap_command: |
           subscription-manager register --username=rh-ee-spk --password=Redhat27 --consumerid=1868e5d9-b6f8-420b-bdf1-895869145db9 
           subscription-manager release --set=9.2
           subscription-manager repos --disable=*
           subscription-manager repos --enable=rhel-9-for-x86_64-baseos-eus-rpms --enable=rhel-9-for-x86_64-appstream-eus-rpms --enable=rhel-9-for-x86_64-highavailability-eus-rpms --enable=openstack-17.1-for-rhel-9-x86_64-rpms --enable=fast-datapath-for-rhel-9-x86_64-rpms --enable=rhceph-6-tools-for-rhel-9-x86_64-rpms
         edpm_network_config_template: |
            ---
            network_config:
            - type: interface
              name: eno3
              use_dhcp: false
              default: false
            - type: interface
              name: eno2
              use_dhcp: false
              dns_servers: ["192.168.122.80"]
              domain: []
              fixedIP: 192.168.122.101
              routes:
              - ip_netmask: 169.254.169.254/32
                next_hop: 192.168.122.1
              - default: true
                next_hop: 192.168.122.1
            - type: vlan
              device: eno2
              vlan_id: 111
              addresses:
              - ip_netmask: 172.17.0.101/24
            - type: vlan
              device: eno2
              vlan_id: 112
              addresses:
              - ip_netmask: 172.18.0.101/24
            - type: vlan
              vlan_id: 113
              device: eno1
              addresses:
              - ip_netmask: 172.19.0.101/24
            - type: sriov_pf
              name: enp4s0f0np0
              use_dhcp: false
              numvfs: 5
            - type: sriov_pf
              name: enp4s0f1np1
              use_dhcp: false
              numvfs: 5        
         # These vars are for the network config templates themselves and are
         # considered EDPM network defaults.
         #neutron_physical_bridge_name: br-ex
         #Neutron_public_interface_name: eno1
         registry_url: quay.io/podified-antelope-centos9
         image_tag: current-podified
         image_prefix: openstack
         edpm_chrony_ntp_servers:
           - pool.ntp.org

         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         ctlplane_dns_nameservers:
           - 192.168.122.1
         dns_search_domains: []
         edpm_kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on tsx=off isolcpus=2-11,14-23"
         edpm_tuned_profile: "cpu-partitioning"
         edpm_nova_libvirt_qemu_group: "hugetlbfs"
         edpm_tuned_isolated_cores: "2-11,14-23"

         gather_facts: false
         enable_debug: false
         # edpm firewall, change the allowed CIDR if needed
         edpm_sshd_configure_firewall: true
         edpm_sshd_allowed_ranges: ['192.168.122.0/24']
         # SELinux module
         #   edpm_selinux_mode: enforcing
         edpm_neutron_sriov_agent_SRIOV_NIC_physical_device_mappings: 'sriov1:enp4s0f0np0,sriov2:enp4s0f1np1'
