apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-sriov
spec:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  services:
    - download-cache
    - bootstrap
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - run-os
    - reboot-os
    - libvirt
    - ovn
    - neutron-sriov
    - neutron-metadata
    - nova-custom-sriov
  baremetalSetTemplate:
    bmhLabelSelector:
      app: sriov
    ctlplaneInterface: eno2
    cloudUserName: cloud-admin
    provisioningInterface: enp1s0
    passwordSecret:
      name: baremetalset-password-secret
      namespace: openstack
  nodes:
    edpm-compute-1:
      hostName: edpm-compute-1
  networkAttachments:
    - ctlplane
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    networks:
      - name: CtlPlane
        subnetName: subnet1
        defaultRoute: true
      - name: InternalApi
        subnetName: subnet1
      - name: Storage
        subnetName: subnet1
      - name: Tenant
        subnetName: subnet1
    managementNetwork: ctlplane
    ansible:
      ansibleUser: cloud-admin
      ansiblePort: 22
      ansibleVars:
         service_net_map:
           nova_api_network: internal_api
           nova_libvirt_network: internal_api
         timesync_ntp_servers:
           - hostname: pool.ntp.org
         # edpm_network_config
         # Default nic config template for a EDPM compute node
         # These vars are edpm_network_config role vars
         edpm_network_config_hide_sensitive_logs: false
         edpm_network_config_template: |
            ---
            network_config:
            - type: interface
              name: eno3
              use_dhcp: false
              default: false
            - type: interface
              name: eno2
              use_dhcp: false
              dns_servers: ["192.168.122.80"]
              domain: []
              addresses:
              - ip_netmask: 192.168.122.100/24
              routes:
              - ip_netmask: 169.254.169.254/32
                next_hop: 192.168.122.1
              - default: true
                next_hop: 192.168.122.1
            - type: vlan
              device: eno2
              vlan_id: 111
              addresses:
              - ip_netmask: 172.17.0.100/24
            - type: vlan
              device: eno2
              vlan_id: 112
              addresses:
              - ip_netmask: 172.18.0.100/24
            - type: vlan
              vlan_id: 113
              device: eno2
              addresses:
              - ip_netmask: 172.19.0.100/24
            - type: sriov_pf
              name: eno1
              use_dhcp: false
              numvfs: 5
            - type: sriov_pf
              name: eno2
              use_dhcp: false
              numvfs: 5           


         # These vars are for the network config templates themselves and are
         # considered EDPM network defaults.
         neutron_physical_bridge_name: br-ex
         neutron_public_interface_name: eth0
         edpm_kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on tsx=off isolcpus=2-11,14-23"
         edpm_tuned_profile: "cpu-partitioning"
         edpm_tuned_isolated_cores: "2-11,14-23"
         ctlplane_mtu: 1500
         ctlplane_subnet_cidr: 24
         ctlplane_gateway_ip: 192.168.122.1
         ctlplane_host_routes:
         - ip_netmask: 0.0.0.0/0
           next_hop: 192.168.122.1
         external_mtu: 1500
         external_cidr: '24'
         external_host_routes: []
         internal_api_mtu: 1500
         internal_api_cidr: '24'
         internal_api_host_routes: []
         storage_mtu: 1500
         storage_cidr: '24'
         storage_host_routes: []
         tenant_mtu: 1500
         tenant_cidr: '24'
         tenant_host_routes: []
         role_networks:
         - InternalApi
         - Storage
         - Tenant
         networks_lower:
           External: external
           InternalApi: internal_api
           Storage: storage
           Tenant: tenant
         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         ctlplane_dns_nameservers:
         - 192.168.122.1
         dns_search_domains: []
         gather_facts: false
         enable_debug: false
         # edpm firewall, change the allowed CIDR if needed
         edpm_sshd_configure_firewall: true
         edpm_sshd_allowed_ranges: ['192.168.122.0/24']
         # SELinux module
         edpm_selinux_mode: enforcing
         edpm_nova_compute_image: "quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified"
         edpm_neutron_sriov_agent_SRIOV_NIC_physical_device_mappings: 'sriov1:eno1,sriov2:eno2'
