---
cifmw_architecture_scenario: "ovs-dpdk-sriov"
_arch_repo: "{{ cifmw_architecture_repo | default('/home/zuul/src/github.com/openstack-k8s-operators/architecture') }}"


# libvirt settings
cifmw_use_libvirt: true
cifmw_libvirt_manager_net_prefix_add: false
cifmw_libvirt_manager_pub_net: ocpbm
cifmw_config_bmh: true
cifmw_libvirt_manager_fixed_networks:
  - ocpbm
  - ocppr
  - osp_external
  - osp_trunk

cifmw_libvirt_manager_configuration:
  networks:
    ocpbm: |
      <network>
        <name>ocpbm</name>
        <forward mode='bridge' />
        <bridge name='ocpbm' />
      </network>
    ocppr: |
      <network>
        <name>ocppr</name>
        <forward mode='bridge' />
        <bridge name='ocppr' />
      </network>
    osp_trunk: |
      <network>
        <name>osp_trunk</name>
        <forward mode='bridge' />
        <bridge name='osp_trunk' />
      </network>
    osp_external: |
      <network>
        <name>osp_external</name>
        <forward mode='bridge' />
        <bridge name='osp_external' />
      </network>
  vms:
    ocp:
      amount: 3
      uefi: true
      root_part_id: 4
      admin_user: core
      image_local_dir: "{{ cifmw_basedir }}/images/"
      disk_file_name: "ocp_master"
      disksize: "100"
      extra_disks_num: 3
      extra_disks_size: "50G"
      memory: 32
      cpus: 10
      nets:
        - ocppr
        - ocpbm
        - osp_trunk
        - osp_external
    controller:
      root_part_id: 4
      image_url: "{{ cifmw_discovered_image_url }}"
      sha256_image_name: "{{ cifmw_discovered_hash }}"
      image_local_dir: "{{ cifmw_basedir }}/images/"
      disk_file_name: "base-os.qcow2"
      disksize: 50
      memory: 8
      cpus: 4
      ip_address:
         address: "192.168.111.9/24"
         gw: "192.168.111.1"
         dns: "192.168.111.1"
      nets:
        - ocpbm
        - osp_trunk

cifmw_config_bmh: true
cifmw_openshift_setup_metal3_watch_all_ns: true


# secrets required by devscripts
cifmw_manage_secrets_citoken_file: "{{ lookup('env', 'HOME') }}/config/ci_token"
cifmw_manage_secrets_pullsecret_file: "{{ lookup('env', 'HOME') }}/config/pull_secret"
